import { useState } from 'react';
import DdlPreviewDialog from './DdlPreviewDialog';
import { notify, sessionOf, getState } from '../state/store';
import { message } from '../state/actions';

interface DraftColumn {
  key: string;
  name: string;
  dataType: string;
  nullable: boolean;
  defaultValue: string;
  comment: string;
  primaryKey: boolean;
  autoIncrement: boolean;
}

interface Props {
  connectionId: string;
  database: string;
  schema: string;
  onClose: () => void;
  /** 실제로 만들어진 뒤 (트리 새로 고침 등) */
  onCreated: () => void;
}

let seq = 0;
function newColumn(dataType: string): DraftColumn {
  seq += 1;
  return { key: `c${seq}`, name: '', dataType, nullable: true, defaultValue: '', comment: '', primaryKey: false, autoIncrement: false };
}

/** 트리에서 '테이블 생성…' 을 눌렀을 때 뜨는 폼. CREATE TABLE 을 만들어 미리보기로 넘긴다. */
export default function CreateTableDialog({ connectionId, database, schema, onClose, onCreated }: Props) {
  const session = sessionOf(connectionId, getState());
  const pg = session?.kind === 'postgres';
  const defaultType = pg ? 'text' : 'varchar(50)';

  const [name, setName] = useState('');
  const [comment, setComment] = useState('');
  const [columns, setColumns] = useState<DraftColumn[]>([
    { ...newColumn(pg ? 'bigint' : 'bigint'), name: 'id', nullable: false, primaryKey: true, autoIncrement: true },
    newColumn(defaultType),
  ]);
  const [preview, setPreview] = useState<string[] | null>(null);

  const patch = (key: string, p: Partial<DraftColumn>) =>
    setColumns((prev) => prev.map((c) => (c.key === key ? { ...c, ...p } : c)));

  const showPreview = async () => {
    if (!name.trim()) { notify('info', '테이블 이름을 입력하세요.'); return; }
    // 이름도 없고 아무 속성도 안 만진 행만 조용히 버린다.
    // 반쯤 채운 행을 소리 없이 빼고 만들면 PK 가 빠진 테이블이 생길 수 있다.
    const meaningful = columns.filter((c) =>
      c.name.trim() || c.primaryKey || c.autoIncrement || c.defaultValue.trim() || c.comment.trim());
    const broken = meaningful.filter((c) => !c.name.trim() || !c.dataType.trim());
    if (broken.length) {
      notify('error', `이름이나 데이터 타입이 빈 컬럼 행이 ${broken.length}개 있습니다. 채우거나 행을 제거하세요.`);
      return;
    }
    const filled = meaningful;
    if (!filled.length) { notify('info', '컬럼을 하나 이상 채워 주세요.'); return; }
    // 자동 증가는 키의 일부여야 하고(MySQL 에러 1075), 기본값과 함께 쓸 수 없다.
    const badAi = filled.find((c) => c.autoIncrement && (!c.primaryKey || c.defaultValue.trim()));
    if (badAi) {
      notify('error', badAi.defaultValue.trim()
        ? `${badAi.name}: 자동 증가 컬럼에는 기본값을 함께 줄 수 없습니다.`
        : `${badAi.name}: 자동 증가 컬럼은 기본키로 지정해야 합니다.`);
      return;
    }
    try {
      const statements = await window.api.ddl.build(connectionId, 'createTable', {
        schema,
        spec: {
          name: name.trim(),
          comment: comment.trim() || null,
          columns: filled.map((c) => ({
            name: c.name.trim(),
            dataType: c.dataType.trim(),
            nullable: c.nullable && !c.primaryKey,
            defaultValue: c.defaultValue.trim() || null,
            comment: c.comment.trim() || null,
            primaryKey: c.primaryKey,
            autoIncrement: c.autoIncrement,
          })),
        },
      });
      setPreview(statements);
    } catch (e) {
      notify('error', message(e));
    }
  };

  return (
    <div className="modal-backdrop" onMouseDown={onClose}>
      <div className="modal wide" onMouseDown={(e) => e.stopPropagation()}>
        <h3>테이블 생성 — {database}{pg ? ` › ${schema}` : ''}</h3>

        <div className="ddl-form-row" style={{ marginBottom: 8 }}>
          <label>테이블 이름 <input className="input" autoFocus value={name} onChange={(e) => setName(e.target.value)} /></label>
          <label>주석 <input className="input" value={comment} onChange={(e) => setComment(e.target.value)} /></label>
        </div>

        <div className="grid-scroll" style={{ maxHeight: 320 }}>
          <table className="meta-table">
            <thead>
              <tr>
                <th>이름</th><th>데이터 타입</th><th>NULL</th><th>기본값</th><th>PK</th>
                <th title={pg ? 'GENERATED BY DEFAULT AS IDENTITY' : 'AUTO_INCREMENT'}>자동증가</th><th>주석</th><th />
              </tr>
            </thead>
            <tbody>
              {columns.map((c) => (
                <tr key={c.key}>
                  <td><input className="input cell" value={c.name} onChange={(e) => patch(c.key, { name: e.target.value })} /></td>
                  <td><input className="input cell mono" value={c.dataType} onChange={(e) => patch(c.key, { dataType: e.target.value })} /></td>
                  <td className="center">
                    <input type="checkbox" checked={c.nullable && !c.primaryKey} disabled={c.primaryKey} onChange={(e) => patch(c.key, { nullable: e.target.checked })} />
                  </td>
                  <td><input className="input cell mono" placeholder="SQL 식" value={c.defaultValue} onChange={(e) => patch(c.key, { defaultValue: e.target.value })} /></td>
                  <td className="center">
                    <input type="checkbox" checked={c.primaryKey} onChange={(e) => patch(c.key, { primaryKey: e.target.checked })} />
                  </td>
                  <td className="center">
                    <input type="checkbox" checked={c.autoIncrement} onChange={(e) => patch(c.key, { autoIncrement: e.target.checked })} />
                  </td>
                  <td><input className="input cell" value={c.comment} onChange={(e) => patch(c.key, { comment: e.target.value })} /></td>
                  <td className="center">
                    <button className="icon-btn" title="행 제거" disabled={columns.length <= 1} onClick={() => setColumns((p) => p.filter((x) => x.key !== c.key))}>×</button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <div className="modal-actions">
          <button className="btn small" onClick={() => setColumns((p) => [...p, newColumn(defaultType)])}>+ 컬럼 추가</button>
          <span className="hint">기본값은 SQL 식 그대로 입력합니다. 예: <code>'A'</code>, <code>0</code>, <code>now()</code></span>
          <div className="spacer" />
          <button className="btn" onClick={onClose}>취소</button>
          <button className="btn primary" onClick={() => void showPreview()}>SQL 미리보기</button>
        </div>

        {preview && (
          <DdlPreviewDialog
            connectionId={connectionId}
            title={`${schema}.${name.trim()} 테이블 생성`}
            statements={preview}
            autoCommit={session?.autoCommit ?? true}
            transactionalDdl={pg}
            onClose={() => setPreview(null)}
            onApplied={() => { onCreated(); onClose(); }}
          />
        )}
      </div>
    </div>
  );
}
